### PR TITLE
feat: improve readability of syntax error messages for eszip builds

### PR DESCRIPTION
**Pull request by Skn0tt**
- chore: write reproduction test
- fix: throw nice error messages for syntax errors

### CODE REVIEW

**Comment by eduardoboucas** [comment]
@Skn0tt what's the status of this one?

**Comment by Skn0tt** [comment]
the status is "I forgot about this and am glad you reminded me". let's see what's missing here 🤔

**Comment by Skn0tt** [comment]
this is blocked by https://github.com/netlify/partner-deno/issues/6. I'll ping Luca, I suppose they forgot about it.

**Comment by Skn0tt** [comment]
it looks like luca already self-assigned the issue two days ago, so let's give it some time :)

**Comment by Skn0tt** [comment]
closing until https://github.com/netlify/partner-deno/issues/6 is resolved

**Pull request closed without merging**
